licenses(["notice"])  # Apache v2

package(default_visibility = ["//visibility:public"])

exports_files(["LICENSE"])

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "noncopyable",
    hdrs = ["noncopyable.h"],
    deps = [],
    alwayslink = True,
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "singleton",
    hdrs = ["singleton.h"],
    deps = [],
    alwayslink = True,
)
