cc_binary (
  name="log_unittest",
  srcs= ["log_unittest.cc"],
  deps = [
    "//sylar:log",
    "@com_google_googletest//:gtest_main",
  ],
)


cc_binary (
  name="env_unittest",
  srcs= ["env_unittest.cc"],
  deps = [
    "//sylar:env",
  ],
)


cc_binary (
  name="config_unittest",
  srcs= ["config_unittest.cc"],
  deps = [
   "//sylar:env",
   "//sylar:log",
   "//sylar:config",
  ],
)