cc_binary (
  name="log_unittest",
  srcs= ["log_unittest.cc"],
  deps = [
   "//sylar:sylar",
    "@com_google_googletest//:gtest_main",
  ],
)


cc_binary (
  name="env_unittest",
  srcs= ["env_unittest.cc"],
  deps = [
    "//sylar:sylar",
  ],
)


cc_binary (
  name="config_unittest",
  srcs= ["config_unittest.cc"],
  deps = [
   "//sylar:sylar",
  ],
)

cc_binary (
  name="thread_unittest",
  srcs= ["thread_unittest.cc"],
  deps = [
   "//sylar:sylar",
  ],
)

cc_binary (
  name="fiber_unittest",
  srcs= ["fiber_unittest.cc"],
  deps = [
   "//sylar:sylar",
  ],
)

cc_binary (
  name="scheduler_unittest",
  srcs= ["scheduler_unittest.cc"],
  deps = [
   "//sylar:sylar",
  ],
)

cc_binary (
  name="iomanager_unittest",
  srcs= ["iomanager_unittest.cc"],
  deps = [
   "//sylar:sylar",
  ],
)